name: Build and Push Docker image

on:
  push:
    branches: [ '**' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-complex

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase
        name: Lowercase the name
        uses: AsZc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.lowercase }}

      - name: Build and push
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          context: ./3_complex_example
          file: ./3_complex_example/Dockerfile
          push: "${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
